tel: '+16135551234'
tel_display: 800 867 5309
seo:
  tagline: Live the dream in an old-style English Cottage
location:
  country: England
  locality: Leamington Spa
  region: Warwickshire
  street_address: 123 Main Street
